<a href="https://colab.research.google.com/github/VineetGp/Jupyter-Notebooks/blob/main/A3_PytonMandatory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
def matrix_mul(A, B):
    r1 = len(A)
    c1 = len(A[0])
    r2 = len(B)
    c2 = len(B[0])
    if(c1!=r2):
      print('Not possible')
      return 0
    else:
      r = []
      for i in range(0,r1):
        t = []
        for j in range(0,c2):
          temp = 0
          for k in range(0,c1):
            temp+= A[i][k]*B[k][j]
          t.append(temp)
        r.append(t)
    return(r)
A = [[1,3,4],[2,5,7],[5,9,6]] 
B = [[1,0,0],[0,1,0],[0,0,1]]
r1 = matrix_mul(A, B)
print(r1)

A = [[1,2],[3,4]]
B = [[1,4],[5,6],[7,8],[9,6]]
r2 = matrix_mul(A, B)

A = [[1,2],[3,4]]
B = [[1,2,3,4,5],[5,6,7,8,9]]
r2 = matrix_mul(A, B)
print(r2)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
Not possible
[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
def normalize(a):
  norm = []
  s = sum(a)
  for i in a:
    norm.append(i/s)
  return norm

def cumsum(b):
  c = []
  for i in range(0,len(b)):
    c.append(sum(b[0:int(i+1)]))
  return c

def pick_a_number_from_list(A):
  norm = normalize(A)
  cum = cumsum(norm)
  num = uniform(0,1)
  for i in range(0,len(cum)):
    if(num>cum[i]):
      continue
    else:
      return i 

def sampling_based_on_magnitude(a):
    b = [0]*len(a)
    result = list(map(list,zip(a,b)))
    for i in range(0,1000):
        index = pick_a_number_from_list(A)
        result[index][1]+=1
    r = sorted(result, key=lambda x:x[1], reverse=True)
    c = [x[0] for x in r]
    print(r)
    print('f({0}) > f({1}) > f({2}) > f({3}) > f({4}) > f({5}) > f({6}) > f({7}) > f({8}) > f({9})'.format(*c))
        
A = [0 ,5 ,27 ,6 ,13 ,28 ,100 ,45 ,10 ,79]
sampling_based_on_magnitude(A)

[[100, 324], [79, 264], [45, 133], [28, 96], [27, 71], [13, 39], [10, 30], [6, 23], [5, 20], [0, 0]]
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:

def replace_digits(String):
  s = []
  for i in range(0,len(String)):
    if(String[i].isnumeric()):
      s.append('#')
    else:
      continue
  r = ''.join(s)
  return r 
a = '#2a$#b%c%561#'
print(replace_digits(a))

b = 'abc'
print(replace_digits(b))

c = '234'
print(replace_digits(c))

####

###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
def median(l):
  n = len(l)
  if(n%2==0):
    m = (l[int(n/2)-1]+l[int((n+2)/2)-1])/2
  else:
    m = l[int(n/2)]
  return m

def display_dash_board(students, marks):
    a = zip(marks,students)
    b = list(a)
    c = sorted(b, reverse=True)
    top_5_students = c[0:5]
    d = sorted(b)
    least_5_students = d[0:5]
    n = len(marks)
    marks.sort()
    if(n%2==0):
      q1 = median(marks[0:int(n/2)])
      q3 = median(marks[int(n/2):])
    else:
      q1 = median(marks[0:int((n-1)/2)])
      q3 = median(marks[int((n+1)/2):])

    students_within_25_and_75 = []
    for i in b:
      if(i[0]>=q1 and i[0]<q3):
        students_within_25_and_75.append(i)
      else:
        continue
    students_within_25_and_75.sort()
    return top_5_students, least_5_students, students_within_25_and_75

def display(lst):
  for i in lst:
    print('{0}  {1}'.format(i[1],i[0]))

students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print('a.')
display(top_5_students)
print('b.')
display(least_5_students)
print('c.')
display(students_within_25_and_75)

22 78
a
student8  98
student10  80
student2  78
student5  48
student7  45
b
student3  12
student4  14
student9  22
student6  43
student1  45
c
student9  22
student6  43
student1  45
student7  45
student5  48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math
def cosine_distance(point,a):
  x = a[0]
  y = a[1]
  p = point[0]
  q = point[1]
  distance = math.acos(((x*p)+(y*q))/((math.sqrt(x**2+y**2))*(math.sqrt(p**2+q**2))))
  return distance

def closest_points_to_p(S, P):
    d = []
    for i in S:
      d.append(cosine_distance(P,i))
    a = zip(d,S)
    b = list(a)
    b.sort()
    c = b[0:5]
    closest_points = []
    for i in c:
      closest_points.append(i[1])
    return closest_points 

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)
points = closest_points_to_p(S, P)
for i in points:
  print(i)


(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
def str_to_coeff(Lines):
  coeff = []
  for i in Lines:
    temp = []
    a = i.split('x')
    temp.append(float(a[0]))
    b = a[1].split('y')
    temp.append(float(b[0]))
    temp.append(float(b[1]))
    coeff.append(temp)
  return coeff

def side(c,p):
  a = (c[0]*p[0]) + (c[1]*p[1]) + (c[2])
  if(a>0):
    return 1
  elif(a<0):
    return -1
  else:
    return 0

def i_am_the_one(red,blue,coeff):
    r = []
    for i in red:
      r.append(side(coeff,i))
    for i in range(1,len(r)):
      if(r[0]==r[i]):
        continue
      else:
        return 0
    b = []
    for i in blue:
      b.append(side(coeff,i))
    for i in range(1,len(b)):
      if(b[0]==b[i]):
        continue
      else:
        return 0
    if(r[0]!=b[0]):
      return 1
    else:
      return 0

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
l = str_to_coeff(Lines)

for i in l:
    result = i_am_the_one(Red, Blue, i)
    if(result == 0):
      print('No')
    elif(result == 1):
      print('Yes')
    else:
      print('Invalid')

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
def curve_smoothing(string):
  s = string.split(',')
  index = nextVal = end = endVal = 0
  for i in range(0,len(s)):
      index = i
      if (s[i]!='_' or index+1==len(s)):
        if(s[i]!='_'):
          nextVal = int(s[i])
        else:
          nextVal = 0
        f = (nextVal+endVal)/(index+1-end)
        for j in range(end, index+1):
          s[j] = int(f)
        end = index
        endVal = f
      index+=1
  return s

S = ["_,_,_,24", "40,_,_,_,60", "80,_,_,_,_", "_,_,30,_,_,_,50,_,_"]
a = []
for i in S:
  a.append(curve_smoothing(i))
print(a)

[[6, 6, 6, 6], [20, 20, 20, 20, 20], [16, 16, 16, 16, 16], [10, 10, 12, 12, 12, 12, 4, 4, 4]]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
def conditional_probabilites(F,S,A):
  n = 0
  d = 0
  for i in A:
    if(i[0]==F and i[1]==S):
      n+=1
    else:
      continue
  for i in A:
    if(i[1]==S):
      d+=1
    else:
      continue
  return n,d
  print('P(F={0}|S=={1})={2}/{3}'.format(F,S,n,d))

def display(l1, l2, A):
  for i in l1:
    for j in l2:
      n,d = conditional_probabilites(i,j,A)
      print('P(F={0}|S=={1})={2}/{3}'.format(i,j,n,d))
    print('-'*100)

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
s1 = set()
for i in A:
  s1.add(i[0])
L1 = list(s1)
L1.sort()
s2 = set()
for i in A:
  s2.add(i[1])
L2 = list(s2)
L2.sort()
display(L1, L2, A)

P(F=F1|S==S1)=1/4
P(F=F1|S==S2)=1/3
P(F=F1|S==S3)=0/3
----------------------------------------------------------------------------------------------------
P(F=F2|S==S1)=1/4
P(F=F2|S==S2)=1/3
P(F=F2|S==S3)=1/3
----------------------------------------------------------------------------------------------------
P(F=F3|S==S1)=0/4
P(F=F3|S==S2)=1/3
P(F=F3|S==S3)=1/3
----------------------------------------------------------------------------------------------------
P(F=F4|S==S1)=1/4
P(F=F4|S==S2)=0/3
P(F=F4|S==S3)=1/3
----------------------------------------------------------------------------------------------------
P(F=F5|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F5|S==S3)=0/3
----------------------------------------------------------------------------------------------------


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
  def string_features(S1, S2):
    s1 = set(S1.split())
    s2 = set(S2.split())
    a = len(s1&s2)
    b = list(s1-s2)
    c = list(s2-s1)      
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print('a. ',a)
print('b. ',b)
print('c. ',c)

a.  7
b.  ['5', 'first', 'F']
c.  ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
from math import log10
def compute_log_loss(A):
    temp = 0
    for i in A:
      y = i[0]
      y1 = i[1]
      temp += ((y*(log10(y1))) + ((1-y)*(log10(1-y1)))) 
    loss = 0-(temp/len(A))
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
